spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/unmatched_system?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true&serverTimezone=GMT%2B8
    ###################以下为druid增加的配置###########################
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置 最小 最大
    druid:
      # 初始化大小
      initial-size: 5
      #最小值
      min-idle: 5
      #最大值
      max-active: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
